desde fractions importar Fraction como Fracción
desde decimal importar Decimal
desde redondeo importar redondear
desde conteoPM importar C

escribir("2.79")
escribir("H -> Hombre")
escribir("S -> Tiene educación secundaria")
escribir("U -> Tiene educacion universitaria")
escribir("a) P( H | S ) =", Fracción(28,28+50))
escribir("b) P( U' | M ) =", Fracción(45+50,45+50+17))

escribir("")
escribir("2.81")
escribir("M -> Cursa Matemáticas")
escribir("H -> Cursa Historia")
escribir("S -> Cursa Psicología")
escribir("a) P( M ∩ H ∩ S | S ) =", Fracción(10,68))
escribir("b) P( M ∩ H | S' ) =", Fracción(22-10,100-68))

escribir("")
escribir("2.83")
escribir("M -> Mujer")
escribir("H -> Hombre")
escribir("D -> Duerme desnuda")
escribir("P -> Duerme en pijama")
escribir("C -> Duerme en camiseta")
prob = Decimal('0.018')
escribir("a) P( M ∩ D ) =", prob)
prob  = Decimal('0.220') + Decimal('0.002') + Decimal('0.160')
prob += Decimal('0.102') + Decimal('0.046') + Decimal('0.084')
escribir("b) P( H ) =", prob)
prob = redondear(0.102/0.614, 3)
escribir("c) P( P | H ) =", prob)
prob = redondear((0.102+0.046)/(0.175+0.134), 3)
escribir("d) P( H | P ∪ C ) =", prob)

escribir("")
escribir("2.85")
escribir("H -> Hombre casado vea programa")
escribir("M -> Mujer casada vea programa")
prob = Decimal('0.7') * Decimal('0.5')
escribir("a) P( H ∩ M ) =", prob)
prob = Decimal('0.35') / Decimal('0.4')
escribir("b) P( H | M ) =", prob)
prob = Decimal('0.5') + Decimal('0.4') - Decimal('0.35')
escribir("c) P( H ∪ M ) =", prob)

escribir("")
escribir("2.87")
escribir("C -> Matrícula de Canada")
escribir("R -> Sea casa rodante")
prob = Fracción('0.09') / Fracción('0.28')
escribir("a) P( C | R ) =", prob)
prob = Fracción('0.09') / Fracción('0.12')
escribir("b) P( R | C ) =", prob)
prob = 1 - 0.09
escribir("c) P( C' ∪ R' ) =", prob)

escribir("")
escribir("2.89")
escribir("I -> Diagnóstico incorrecto")
escribir("D -> Demanda")
prob = Decimal('0.9') * (1 - Decimal('0.7'))
escribir("P( D | I ) =", prob)

escribir("")
escribir("2.91")
prob = Fracción(4,10)
prob += Fracción(6,10)*Fracción(C(1,1)*C(7,2),C(8,3))
escribir("P =", prob)

escribir("")
escribir("2.93")
escribir("C1 -> Carro 1 dispoible")
escribir("C2 -> Carro 2 disponible")
prob = 1 - (2 * Decimal('0.96') - Decimal('0.96') ** 2)
escribir("a) P( C1' ∩ C2' ) =", prob)
prob = 2 * Decimal('0.96') - Decimal('0.96') ** 2
escribir("b) P( C1 ∪ C2 ) =", prob)

escribir("")
escribir("2.95")
escribir("T1 -> Bolsa 1 frasco tiroides")
escribir("T2 -> Bolsa 2 frasco tiroides")
escribir("A1 -> Bolsa 1 frasco aspirina")
escribir("A2 -> Bolsa 2 frasco aspirina")
prob = Fracción(3,5)*Fracción(2,6)
escribir("a) P( T1 ∩ T2 ) =", prob)
prob = Fracción(2,5)*Fracción(4,6)
escribir("b) P( T1' ∩ T2' ) =", prob)
prob = 1 - Fracción(3,5)*Fracción(2,6)
prob -= Fracción(2,5)*Fracción(3,6)
escribir("c) P( S - (T1 ∩ T2) - (A1 ∩ A2) ) =", prob)

escribir("")
escribir("2.97")
prob = Fracción(15,20)
prob *= Fracción(14,19)
prob *= Fracción(13,18)
prob *= Fracción(12,17)
escribir("a) Forma 1, P =", prob)
prob = Fracción(C(15,4),C(20,4))
escribir("b) Forma 2, P =", prob)

escribir("")
escribir("2.99")
escribir("F -> Sistema funciona")
escribir("A -> Componente A funciona")
escribir("C -> Componente C funciona")
escribir("D -> Componente D funciona")
escribir("E -> Componente E funciona")
escribir("A2 -> Bolsa 2 frasco aspirina")
prob = 1 - (1 - Decimal('0.7')**2)*(1 - Decimal('0.8')**3)
escribir("a) P(F) =", prob)
prob = redondear((0.3 * 0.8**3)/0.75112, 4)
escribir("b) P( F ∩ A' | F) = P( A' ∩ C ∩ D ∩ E | F) =", prob)