from fractions import Fraction as Frac
from decimal import Decimal
from typing import Union
from redondeo.redondeo import redondear
from estadistica.conteo_pm import combs

prob: Union[Decimal, Frac]

print("2.79")
print("H -> Hombre")
print("S -> Tiene educación secundaria")
print("U -> Tiene educacion universitaria")
print("a) P( H | S ) =", Frac(28, 28+50))
print("b) P( U' | M ) =", Frac(45+50, 45+50+17))

print("")
print("2.81")
print("M -> Cursa Matemáticas")
print("H -> Cursa Historia")
print("S -> Cursa Psicología")
print("a) P( M ∩ H ∩ S | S ) =", Frac(10, 68))
print("b) P( M ∩ H | S' ) =", Frac(22-10, 100-68))

print("")
print("2.83")
print("M -> Mujer")
print("H -> Hombre")
print("D -> Duerme desnuda")
print("P -> Duerme en pijama")
print("C -> Duerme en camiseta")
prob = Decimal('0.018')
print("a) P( M ∩ D ) =", prob)
prob = Decimal('0.220') + Decimal('0.002') + Decimal('0.160')
prob += Decimal('0.102') + Decimal('0.046') + Decimal('0.084')
print("b) P( H ) =", prob)
prob = redondear(0.102/0.614, 3)
print("c) P( P | H ) =", prob)
prob = redondear((0.102+0.046)/(0.175+0.134), 3)
print("d) P( H | P ∪ C ) =", prob)

print("")
print("2.85")
print("H -> Hombre casado vea programa")
print("M -> Mujer casada vea programa")
prob = Decimal('0.7') * Decimal('0.5')
print("a) P( H ∩ M ) =", prob)
prob = Decimal('0.35') / Decimal('0.4')
print("b) P( H | M ) =", prob)
prob = Decimal('0.5') + Decimal('0.4') - Decimal('0.35')
print("c) P( H ∪ M ) =", prob)

print("")
print("2.87")
print("C -> Matrícula de Canada")
print("R -> Sea casa rodante")
prob = Frac('0.09') / Frac('0.28')
print("a) P( C | R ) =", prob)
prob = Frac('0.09') / Frac('0.12')
print("b) P( R | C ) =", prob)
prob = Decimal('1') - Decimal('0.09')
print("c) P( C' ∪ R' ) =", prob)

print("")
print("2.89")
print("I -> Diagnóstico incorrecto")
print("D -> Demanda")
prob = Decimal('0.9') * (1 - Decimal('0.7'))
print("P( D | I ) =", prob)

print("")
print("2.91")
print("C -> Casa abierta")
print("L -> Llaves abran casa")
prob = Frac(4, 10)
prob += Frac(6, 10)*Frac(combs(1, 1)*combs(7, 2), combs(8, 3))
print("P(C ∪ (C' ∩ A)) = P(C) + P(C')P(A | C') =", prob)

print("")
print("2.93")
print("C1 -> Carro 1 dispoible")
print("C2 -> Carro 2 disponible")
prob = 1 - (2 * Decimal('0.96') - Decimal('0.96') ** 2)
print("a) P( C1' ∩ C2' ) =", prob)
prob = 2 * Decimal('0.96') - Decimal('0.96') ** 2
print("b) P( C1 ∪ C2 ) =", prob)

print("")
print("2.95")
print("T1 -> Bolsa 1 frasco tiroides")
print("T2 -> Bolsa 2 frasco tiroides")
print("A1 -> Bolsa 1 frasco aspirina")
print("A2 -> Bolsa 2 frasco aspirina")
prob = Frac(3, 5)*Frac(2, 6)
print("a) P( T1 ∩ T2 ) =", prob)
prob = Frac(2, 5)*Frac(4, 6)
print("b) P( T1' ∩ T2' ) =", prob)
prob = 1 - Frac(3, 5)*Frac(2, 6)
prob -= Frac(2, 5)*Frac(3, 6)
print("c) P( S - (T1 ∩ T2) - (A1 ∩ A2) ) =", prob)

print("")
print("2.97")
prob = Frac(15, 20)
prob *= Frac(14, 19)
prob *= Frac(13, 18)
prob *= Frac(12, 17)
print("a) Forma 1, P =", prob)
prob = Frac(combs(15, 4), combs(20, 4))
print("b) Forma 2, P =", prob)

print("")
print("2.99")
print("F -> Sistema funciona")
print("A -> Componente A funciona")
print("C -> Componente C funciona")
print("D -> Componente D funciona")
print("E -> Componente E funciona")
print("A2 -> Bolsa 2 frasco aspirina")
prob = 1 - (1 - Decimal('0.7')**2)*(1 - Decimal('0.8')**3)
print("a) P(F) =", prob)
prob = redondear((0.3 * 0.8**3)/0.75112, 4)
print("b) P( F ∩ A' | F) = P( A' ∩ C ∩ D ∩ E | F) =", prob)
